### ISSUE TITLE
bot not runing

### ISSUE THREAD

**Issue by DynamiteCraft** [Viir/bots#54]
every time i run it it just says 

idk how to fix this
"----
EVE Online framework status:
Last reading from game client: None so far
Last result from volatile process is: Nothing
Current activity: Stop session (Create volatile process failed with exception: System.Exception: Failed to setup the volatile process: System.Exception
 ---> Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (47,29): error CS1069: The type name 'SHA256Managed' could not be found in the namespace 'System.Security.Cryptography'. This type has been forwarded to assembly 'System.Security.Cryptography, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at BotLabClient.VolatileProcess.RunScript(String script)
   --- End of inner exception stack trace ---
   at BotLabClient.VolatileProcess..ctor(Func`2 getFileFromHashSHA256, String csharpScriptCode, Object scriptGlobals)
   at BotLab.Client.PlaySession.PerformAgentTask(StartTask startTask))"

**Comment by Viir** [comment]
Hello and Welcome!
Thank you for the report. I see there were outdated links to scripts that did not work anymore and crashed with the error mentioning `SHA256Managed`. I updated the links now.

Here is a link to a new script: https://catalog.botlab.org/999f03ff3e728e68
