### ISSUE TITLE
getting the followwing issue, kindly help

### ISSUE THREAD

**Issue by officialsiddhantb** [Viir/bots#60]
EVE Online framework status:
Last reading from game client: None so far
Last result from volatile process is: Nothing
Current activity: Stop session (Create volatile process failed with exception: System.Exception: Failed to setup the volatile process:Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (10,1): error CS0006: Metadata file 'sha256:4c5426c5a70c9e01382884f1e860bd0eb24e46c3705689a7d6c3ab94df56c142' could not be found
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Pine.VolatileProcess.RunScript(String script)
   at Pine.VolatileProcess..ctor(Func`2 getFileFromHashSHA256, String csharpScript)
   at BotLab.Client.PlaySession.PerformTask(Task task))

**Comment by Viir** [comment]
That error message means your bot program failed because it did not find the file with hash 4c5426c5a70c9e01382884f1e860bd0eb24e46c3705689a7d6c3ab94df56c142
It looks like 4c5426c5a70c9e01382884f1e860bd0eb24e46c3705689a7d6c3ab94df56c142 is a custom assembly that is specific to your private bot program.
To fix this issue, include the file with hash 4c5426c5a70c9e01382884f1e860bd0eb24e46c3705689a7d6c3ab94df56c142 into the composition that you load as the bot.
Let me know in case you have problems updating your bot program.
